### PR TITLE
[WIP] Remove website app

### PR DESCRIPTION
**Pull request by jlauinger**
This PR removes the website app and dependencies from pyophase. The website creates a lot of unnecessary overhead compared to its benefits. A better solution is to create static CMS pages on the regular D120 website.

**Important:**
This PR may be merged earliest after the current Ophase WiSe 2018 has finished.

### CODE REVIEW

**Comment by bhaettasch** [comment]
Instead of totally removing it, can we have some endpoints still providing the semantic web information, the date (and maybe other information like if the staff registration is open) to be automatically accessed/imported by the django cms?

**Comment by jlauinger** [comment]
:+1: on @bhaettasch's comment, and I would suggest it is probably best to have such endpoints in the corresponding apps (staff, ophasebase, ...)?

**Comment by bhaettasch** [comment]
Sounds reasonable to distribute them to the different apps. We should nevertheless use an uniform url schema for that.

**Comment by jlauinger** [comment]
Maybe we could use `/api/`?

I need some help on 4de67e4 regarding a best practice for removing apps from existing projects entirely. My solution adds a migration to ophasebase (which I determined to be the *least likely* to be removed). The migration drops all tables previously defined by the website app using raw `migrations.RunSQL` operations. `IF EXISTS` makes sure the migration works on newly installed instances, too.

**Comment by jlauinger** [comment]
Note that the much cleaner use of `migrations.DeleteModel` doesn't work from a foreign app. In order to use that, we would need to retain the website migrations, add a new one deleting all models, and keep the website app in the INSTALLED_APPS setting.

**Comment by jlauinger** [comment]
Actually I don't like `/api/` that much any more, especially for semantic web information...

**Comment by ckleemann** [comment]
> Note that the much cleaner use of `migrations.DeleteModel` doesn't work from a foreign app. In order to use that, we would need to retain the website migrations, add a new one deleting all models, and keep the website app in the INSTALLED_APPS setting.

The best solution I found is to run ```./manage.py migrate website zero```. Therefor the migration files still must exist. So migration path would be the following for production: migrate zero -> pull this changes.

**Comment by jlauinger** [comment]
@ckleemann I rebased this branch and squashed afe134c and b535e40 into 
da5e8a0, which now resembles a clean rename.

**Comment by jlauinger** [comment]
> > Note that the much cleaner use of `migrations.DeleteModel` doesn't work from a foreign app. In order to use that, we would need to retain the website migrations, add a new one deleting all models, and keep the website app in the INSTALLED_APPS setting.
> 
> The best solution I found is to run `./manage.py migrate website zero`. Therefor the migration files still must exist. So migration path would be the following for production: migrate zero -> pull this changes.

Ah, I see. True, `migrate .. zero` and then pulling these changes would allow to remove the migrations from the codebase, while still using clean migrations. However, I currently still like the explicit migration more than this approach, because it removes a manual step, and leaves explicit evidence in the codebase of what was happening to the old, existing data.

**Comment by ckleemann** [comment]
> > > Note that the much cleaner use of `migrations.DeleteModel` doesn't work from a foreign app. In order to use that, we would need to retain the website migrations, add a new one deleting all models, and keep the website app in the INSTALLED_APPS setting.
> > 
> > 
> > The best solution I found is to run `./manage.py migrate website zero`. Therefor the migration files still must exist. So migration path would be the following for production: migrate zero -> pull this changes.
> 
> Ah, I see. True, `migrate .. zero` and then pulling these changes would allow to remove the migrations from the codebase, while still using clean migrations. However, I currently still like the explicit migration more than this approach, because it removes a manual step, and leaves explicit evidence in the codebase of what was happening to the old, existing data.

On the other side it add another pip requirement and the table names could never be used in the future. So the manual sql command could be the source for some hard to find bugs. In my point of view the migrate zero approach is cleaner regarding the development. But it has the drawback of missing documentation of what happened to the website app for ops.

**Comment by miterion** [comment]
Done in #472

**Pull request closed without merging**
