### PR TITLE
Integrated TUID (SSO) for staff registration

### PR DESCRIPTION
**Pull request by bhaettasch**
This will force a login with TUID for staff registration and link a sso user to a person. This will allow displaying pages for individual users like clothing ordering or the next shifts/mandatory meetings etc. later (not implemented yet).

Added pyTUID to requirements and used as a middleware
Added django-sslserver as cas requires ssl -- use manage.py runsslserver to start a local test instance
Adapted models, views and templates
Quickfix for staff registration and mail sending test, replace with fake sso later (TODO)

### CODE REVIEW

**Comment by bhaettasch** [comment]
CAS Provider has to unlock the urls used before this can be used in production.
Testint with localhost is already possible.

**Comment by bhaettasch** [comment]
Selenium tests have to be adapted, too...

**Comment by jnhmn** [comment]
The whole domain should already be on the whitelist.
Please verify.
And documentation is needed, which paths need to be on the whitelist if the catch-all rule will eventually be discarded.

**Comment by bhaettasch** [comment]
Linkbased form prefill won't work anymore, too and will be removed.

**Comment by bhaettasch** [comment]
I think this is ready for production to make the developement and testing of further features possible, which will be introduced with another pull request.

**Pull request merged**
