### PR TITLE
[WIP] Add thresholds for tutor registration

### PR DESCRIPTION
**Pull request by jlauinger**
It is already possible to close the tutor's registration. However, doing so requires constant polling by the Head of Ophase to recognize on time when there are enough tutors registered.

This PR will add functionality to set thresholds inside the GroupCategory model both for a warning and for a hard cut.

`warning_threshold`: If more than this amount of tutors have already registered, a warning is shownon the registration page.

`max_threshold`: Past this amount, no registration is possible anymore from the client app.

### CODE REVIEW

**Comment by ckleemann** [comment]
I disabled the comments from coveralls for this repo now and set the _Coverage Decrease Threshold for failure_ to **1%** which should be more then enough.

**Comment by bhaettasch** [comment]
This pull request is still marked as _work in progress_. What work has to be done before it can be merged?

**Comment by jlauinger** [comment]
Almost all work:

 - [x] introduce thresholds to model
 - [ ] adjust registration template to show a warning if `show_warning() == True`
 - [ ] adjust registration controller to throw an error and not create new staff objects if `still_tutors_wanted() == False`
 - [ ] adjust registration template to replace the form with a suitable message if `still_tutors_wanted() == False`
 - [ ] provide translations
 - [ ] add unit tests

Possible additional features:

 - [ ] from the model's `save` method, queue sending an email to the heads of ophase when either threshold condition changes

**Comment by jlauinger** [comment]
Closing this. The work already done is 4 years old, pyophase structure has changed a lot since then. It also isn't a lot of work, so it's not a big loss to just throw it away.

**Pull request closed without merging**
